# Generated by Django 5.1.1 on 2024-10-29 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_work', '0002_studentwork_group_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwork',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата приєднання'),
        ),
    ]
